//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Offer
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public string StateName { get; set; }
        public string Position { get; set; }
        public int Wage { get; set; }
        public int WorkingHours { get; set; }
        public bool Overtime { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Link { get; set; }
    
        public virtual City City { get; set; }
    }
}
